language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

env:
  - PYCOIN_NATIVE=openssl

install:
  - pip install coverage coveralls

before_script:
  - python setup.py install

script:
  - coverage run --source="btctxstore" setup.py test

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
